/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ccj_ffmpeg_CcjPlayer */

#ifndef _Included_com_ccj_ffmpeg_CcjPlayer
#define _Included_com_ccj_ffmpeg_CcjPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ccj_ffmpeg_CcjPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ccj_ffmpeg_CcjPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_ccj_ffmpeg_CcjPlayer_sound
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
